deployment: demo
organisation: ourvoice.app
roles:
  - name: user
    permissions:
      - read:all
      - edit:self
      - delete:self
  - name: moderator
    permissions:
      - read:all
      - edit:all
      - delete:all
  - name: admin
    permissions:
      - manage:self
      - read:all
      - edit:all
      - delete:all
  - name: super
    permissions:
      - manage:all
      - read:all
      - edit:all
      - delete:all
allowedEmails:
  - user@ourvoice.app
moderators:
  - deployment_admin@ourvoice.app
  - moderator1@ourvoice.app
  - moderator2@ourvoice.app
authModules:
  - EmailPassword
  - Passwordless
  - Verify
  - Dashboard
logo: /hero-image.png
deploymentLogo: /dca_logo.png
slogan: 'Are you ready to share experiences, ask questions and propose solutions with your colleagues?'
moderatorCount: 1
postFrequency:
  unit: 'minutes'
  value: 1
persistNickNames: true
attachmentBucket: test-bucket
