deployment: demo
organisation: ourvoice.app
roles:
  - name: user
    permissions:
      - read:all
      - edit:self
      - delete:self
  - name: moderator
    permissions:
      - read:all
      - edit:all
      - delete:all
  - name: admin
    permissions:
      - manage:self
      - read:all
      - edit:all
      - delete:all
  - name: super
    permissions:
      - manage:all
      - read:all
      - edit:all
      - delete:all
allowedEmails:
  - user@ourvoice.app
  - user1@ourvoice.app
moderators:
  - odeployment_admin@ourvoice.app
  - moderator1@ourvoice.app
  - moderator2@ourvoice.app
authModules:
  - EmailPassword
  - Passwordless
  - Verify
  - Dashboard
heroImage:
logo: /ourvoice_logo_new.png
deploymentLogo: ourvoice_logo_nteu_dark.svg
slogan: 'Welcome to the NTEU OurVoice Community Platform'
moderatorCount: 1
postFrequency:
  unit: 'minutes'
  value: 1
persistNickNames: action
attachmentBucket: test-bucket
allowDownvote: true
contentWarningLink: 'https://itstopswithme.humanrights.gov.au/take-action/support-services'
moderationCategories:
  - key: identifiable
    label: 'Potentially identifiable details'
  - key: guidelines_violation
    label: 'Guidelines violation'
  - key: content_warning
    label: 'Content warning'
