version: '3.8'

# List of networks
networks:
  backend:
  frontend:
    driver: bridge

services:
# Postgresql DB
  db:
    image: postgres:15-alpine
    container_name: ourvoice-app-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # mount db volume to the container
      - ./db/data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB_PORT}:5432
    networks:
      - backend

volumes:
  db:
    name: backend