deployment: demo
organisation: ourvoice.app
roles:
  - name: user
    permissions:
      - read:all
      - edit:self
      - delete:self
  - name: moderator
    permissions:
      - read:all
      - edit:all
      - delete:all
  - name: admin
    permissions:
      - manage:self
      - read:all
      - edit:all
      - delete:all
  - name: super
    permissions:
      - manage:all
      - read:all
      - edit:all
      - delete:all
allowedEmails:
  - user@ourvoice.app
moderators:
  - deployment_admin@ourvoice.app
  - moderator1@ourvoice.app
  - moderator2@ourvoice.app
authModules:
  - EmailPassword
  - Passwordless
  - Verify
  - Dashboard
logo: /ourvoice_logo.svg
slogan: 'This is the deployment slogan text from config.yml file'
moderatorCount: 3
postFrequency:
  unit: 'hours'
  value: 1
persistNickNames: true
